//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int MsgID { get; set; }
        public string MsgTitle { get; set; }
        public string MsgText { get; set; }
        public string MsgType { get; set; }
        public string MsgPhoto { get; set; }
        public System.DateTime MsgTime { get; set; }
        public Nullable<int> MsgHit { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
